# Generated by Django 5.0.1 on 2026-02-12 14:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BINANCE', 'Binance'), ('COINBASE', 'Coinbase'), ('KRAKEN', 'Kraken')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('api_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'brokers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('trading_symbol', models.CharField(max_length=50)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='tick_consumer.broker')),
            ],
            options={
                'db_table': 'scripts',
                'ordering': ['name'],
                'unique_together': {('broker', 'trading_symbol')},
            },
        ),
        migrations.CreateModel(
            name='Ticks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick_value', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('volume', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('received_at_producer', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticks', to='tick_consumer.script')),
            ],
            options={
                'db_table': 'ticks',
                'ordering': ['-received_at_producer'],
                'indexes': [models.Index(fields=['script', '-received_at_producer'], name='ticks_script__f7163d_idx'), models.Index(fields=['-received_at_producer'], name='ticks_receive_39fead_idx')],
            },
        ),
    ]
