# Generated by Django 5.0.1 on 2026-02-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tick_consumer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticks',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True),
        ),
    ]
